
dataset: [mpi3d]
vae: 
  exp_params:
    # kld_weight: [0.01, 0.1, 1.0, 10, 100]
    # kld_weight: [1.0, 100.0]
    kld_weight: [1.0]

model_type: [vae]

probe:
  rff_sigma_scale: ['const']
  # rff_sigma_gain: [20.0, 2.0, 0.2, 0.02, 0.002, 0.0002]
  hidden_dim: [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
  # hidden_dim: [32, 64, 512]
  # hidden_dim: [16, 32, 64, 128, 256, 512, 1024]
  # hidden_dim: [16, 64, 256, 1024, 4096]
  rff_sigma_gain: [0.1, 0.08, 0.04, 0.02]


  hidden_layers: [0]
  lr: [0.0002]
