dataset: [mpi3d]
model_type: [raw_data, noisy_uniform_mix_labels]


probe:
  # hidden_multiplier: [0, 2, 4, 8, 12, 16, 32, 64, 128, 256, 512]
  hidden_multiplier: [512]
  lr: [0.0004]
  batch_size: [128]
  cross_ent_mult: [1.0, 0.28571, 0.1]
