dataset: [mpi3d]
pretrained: [True]
model_type: [almost_uniform_mix_labels]

probe:
  hidden_multiplier: [0]
  # hidden_multiplier: [0, 2, 4, 8, 12, 16, 32, 64, 128, 256, 512]
  # hidden_multiplier: [0, 2, 4, 8, 12, 16, 32, 64, 128, 256, 512]

  noise_std_mult: [0.001, 0.005,  0.01, 0.02, 0.04, 0.05]
  lr: [10.0, 2.0, 1.0, 0.8]