
dataset: [dsprites]
model_type: [raw_data, resnet18]

probe:
  hidden_dim: [0]
  hidden_layers: [0]
  rff_sigma_gain: [0.1]
  lr: [0.0002]
  hidden_dim: [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
  # hidden_dim: [32, 64, 512]
