
dataset: [mpi3d]
model_type: [almost_uniform_mix_labels, noisy_labels]

probe:
  hidden_dim: [0]
  hidden_layers: [0]
  # rff_sigma_gain: [10.0 ,1.0, 0.1, 0.01]
  # rff_sigma_gain: [0.1, 0.01]
  # rff_sigma_gain: [0.2, 0.1, 0.08, 0.04, 0.02, 0.01]
  # rff_sigma_gain: [0.2, 0.1, 0.08, 0.04, 0.02, 0.01]
  rff_sigma_gain: [0.2]
  lr: [0.02]
  hidden_dim: [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
  # hidden_dim: [16, 128, 512]
