dataset: [mpi3d]
pretrained: [True]
model_type: [almost_uniform_mix_labels]

probe:
  # hidden_multiplier: [0, 2, 4, 8, 12, 16, 32, 64, 128, 256, 512]
  # hidden_multiplier: [0, 2, 4, 8, 12, 16, 32, 64, 128, 256, 512]
  hidden_multiplier: [0, 32]

  lr: [0.0008, 0.0004]
  batch_size: [32]
  cross_ent_mult: [1.0, 0.2, 0.1]

  # hidden_multiplier: [0, 32, 128]
  # lr: [ 0.1, 0.01, 0.001]
  # batch_size: [32, 64, 128]