batch_size: 64
cfg_id: 28
dataset: dsprites
dataset_path: ./data/disent_indommain/
dry-run: false
epochs: 100
experiment_arguments:
  vae:
    exp_params:
      hsic_reg_version: v1
      kld_weight: 10.0
    model_params:
      alpha: 100000.0
full_title: 2022Sep08-214017_unsup_vae_dsprites_hsicbetavae_vae.exp_params.hsic_reg_version=v1;
  vae.exp_params.kld_weight=10.0; vae.model_params.alpha=100000.0
gamma: 0.7
log_interval: 10
lr: 0.001
model:
  batch_size: 64
  epochs: 100
  gamma: 0.1
  lr: 0.001
  optim_steps:
  - 70
  - 90
model_type: vae
name: pretrained
noise_std: 0.0
num_workers: 2
out_dir: ./results/2022Sep08-214017_unsup_vae_dsprites_hsicbetavae/0028_vae.exp_params.hsic_reg_version_v1__vae.exp_params.kld_weight_10.0__vae.model_params.alpha_100000.0/4
pretrained: true
probe:
  batch_size: 128
  cross_ent_mult: 1.0
  data_fraction: 1.0
  epochs: 100
  gamma: 0.1
  hidden_layers: 2
  hidden_multiplier: 128
  lr: 0.0004
  max_depth: 50
  max_leaf_nodes: None
  noise_std_mult: 1.0
  num_trees: 100
  optim_steps:
  - 70
  - 90
  rf_lr: 0.1
  type: tree_ens_xgb
run_id: 4
save_model: false
save_representation_datasets: true
seed: 1
supervision: false
title: vae.exp_params.hsic_reg_version=v1; vae.exp_params.kld_weight=10.0; vae.model_params.alpha=100000.0
vae:
  data_params:
    data_path: Data/
    num_workers: 4
    patch_size: 2
    train_batch_size: 2
    val_batch_size: 2
  exp_params:
    LR: 0.002
    hsic_every_epoch: true
    hsic_reg_version: v1
    kld_weight: 10.0
    manual_seed: 1265
    num_sample_reparam: 3
    num_samples_hisc: 512
    s_x: 10000
    s_y: 10000
    scheduler_gamma: 0.95
    weight_decay: 0.0
  logging_params:
    name: VAE
    save_dir: logs/
  model_params:
    alpha: 100000.0
    beta: 1.0
    in_channels: 1
    latent_dim: 10
    loss_type: H
    model_type: smallhsicbeta
    name: HsicBetaVAE
    recons_type: bce
  trainer_params:
    gpus:
    - 0
    max_epochs: 10
