
dataset: [mpi3d]
model_type: [raw_data]

probe:
  hidden_dim: [0]
  hidden_layers: [0]

  lr: [0.0002]
  hidden_dim: [16, 32, 64, 128, 256, 512, 1024, 2048, 4084]
  # hidden_dim: [32, 64, 512, 2048]
  # hidden_dim: [16, 64, 256, 1024, 4096]
  # rff_sigma_gain: [0.8, 0.4, 0.2, 0.1, 0.08, 0.04, 0.02, 0.01, 0.008]
  rff_sigma_gain: [0.8, 1.2]

  # rff_sigma_gain: [0.08]
  # seem to be that gain 0.08 is best overall
