dataset: [cars3d]
pretrained: [True]
model_type: [resnet18, raw_data]

probe:
  # hidden_multiplier: [0, 2, 4, 8, 12, 16, 32, 64, 128, 256, 512]
  hidden_multiplier: [0, 8, 64, 128]
  # hidden_multiplier: [0, 32]

  lr: [0.0001, 0.0002, 0.0004, 0.0008]

  batch_size: [128]
  epochs: [500]
  # cross_ent_mult: [1.0, 0.2, 0.1]

  # hidden_multiplier: [0, 32, 128]
  # lr: [ 0.1, 0.01, 0.001]
  # batch_size: [32, 64, 128]