
dataset: [mpi3d]
model_type: [raw_data, noisy_labels, almost_uniform_mix_labels, resnet18, vae ]

probe:
  # data_fraction: [10, 100, 1000, 10000] #[128, 100, 1000, 10000]
  # hidden_multiplier: [0, 32, 128, 512]
  hidden_multiplier: [0, 2, 4, 8, 12, 16, 32, 64, 128, 256, 512]
  # hidden_multiplier: [0, 2, 4, 8, 12, 16, 32, 64, 128, 256, 512]

  lr: [0.0004]